# Generated by Django 5.0 on 2025-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_dataupload_error_message_dataupload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialpersona',
            name='training_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='memorialpersona',
            name='training_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memorialpersona',
            name='training_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
