# Generated by Django 4.2.27 on 2026-02-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_memorialpersona_training_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialpersona',
            name='training_accuracy',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='memorialpersona',
            name='training_step_message',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='memorialpersona',
            name='training_data',
            field=models.JSONField(default=list),
        ),
    ]
